package xaero.common.minimap.radar.category.setting;

import java.util.List;
import java.util.Map;
import net.minecraft.class_1074;
import xaero.common.category.setting.ObjectCategorySetting;
import xaero.common.category.ui.setting.CategorySettingsUIEditorSettingType;
import xaero.common.graphics.CursorBox;
import xaero.common.minimap.radar.category.EntityRadarCategoryConstants;
import xaero.common.settings.ModSettings;

public class EntityRadarCategorySettings {
   public static final Map<String, ObjectCategorySetting<?>> SETTINGS = EntityRadarCategoryConstants.MAP_FACTORY.get();
   public static final List<ObjectCategorySetting<?>> SETTINGS_LIST = EntityRadarCategoryConstants.LIST_FACTORY.get();
   public static final ObjectCategorySetting<Boolean> DISPLAYED = ObjectCategorySetting.Builder.<Boolean>getDefault()
      .setId("displayed")
      .setDefaultValue(true)
      .setDisplayName("gui.xaero_radar_displayed")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(1)
      .setIndexReader(x -> x == 1)
      .setIndexWriter(x -> x ? 1 : 0)
      .setUiValueNameProvider(ModSettings::getTranslation)
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> COLOR = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("color")
      .setDefaultValue(13.0)
      .setDisplayName("gui.xaero_radar_dots_color")
      .setSettingUIType(CategorySettingsUIEditorSettingType.EXPANDING)
      .setUiFirstOption(-1)
      .setUiLastOption(15)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(
         x -> x == -1.0
               ? "# " + class_1074.method_4662("gui.xaero_radar_dots_color_team_colour", new Object[0])
               : "§" + ModSettings.ENCHANT_COLORS[x.intValue()] + "#§r " + class_1074.method_4662(ModSettings.ENCHANT_COLOR_NAMES[x.intValue()], new Object[0])
      )
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> ICONS = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("icons")
      .setDefaultValue(1.0)
      .setDisplayName("gui.xaero_radar_icons_displayed")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(2)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(x -> class_1074.method_4662(ModSettings.ENTITY_ICONS_OPTIONS[x.intValue()], new Object[0]))
      .setTooltip(new CursorBox("gui.xaero_box_entity_radar_icons"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> NAMES = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("names")
      .setDefaultValue(0.0)
      .setDisplayName("gui.xaero_radar_names_displayed")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(2)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(x -> class_1074.method_4662(ModSettings.ENTITY_NAMES_OPTIONS[x.intValue()], new Object[0]))
      .setTooltip(new CursorBox("gui.xaero_box_entity_radar_names"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> DOT_SIZE = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("dotSize")
      .setDefaultValue(2.0)
      .setDisplayName("gui.xaero_dots_size")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(1)
      .setUiLastOption(4)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(x -> x.intValue() + "")
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> ICON_SCALE = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("iconScale")
      .setDefaultValue(1.0)
      .setDisplayName("gui.xaero_entity_heads_scale")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(5)
      .setUiLastOption(40)
      .setIndexReader(x -> (double)x * 0.05)
      .setIndexWriter(x -> (int)(x / 0.05))
      .setUiValueNameProvider(x -> String.format("%.2f", x))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> HEIGHT_LIMIT = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("heightLimit")
      .setDefaultValue(20.0)
      .setDisplayName("gui.xaero_height_limit")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(2)
      .setUiLastOption(410)
      .setIndexReader(x -> (double)x * 5.0)
      .setIndexWriter(x -> (int)(x / 5.0))
      .setUiValueNameProvider(x -> x.intValue() + "")
      .setTooltip(new CursorBox("gui.xaero_box_height_limit"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Boolean> HEIGHT_FADE = ObjectCategorySetting.Builder.<Boolean>getDefault()
      .setId("heightBasedFade")
      .setDefaultValue(true)
      .setDisplayName("gui.xaero_entity_depth")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(1)
      .setIndexReader(x -> x == 1)
      .setIndexWriter(x -> x ? 1 : 0)
      .setUiValueNameProvider(ModSettings::getTranslation)
      .setTooltip(new CursorBox("gui.xaero_box_entity_depth"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> DISPLAY_Y = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("displayHeight")
      .setDefaultValue(0.0)
      .setDisplayName("gui.xaero_entity_display_height")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(3)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(
         x -> x.intValue() == 0
               ? class_1074.method_4662("gui.xaero_off", new Object[0])
               : (
                  x.intValue() == 1
                     ? class_1074.method_4662("gui.xaero_entity_display_height_actual", new Object[0])
                     : (
                        x.intValue() == 2
                           ? class_1074.method_4662("gui.xaero_entity_display_height_relative", new Object[0])
                           : class_1074.method_4662("gui.xaero_entity_display_height_direction", new Object[0])
                     )
               )
      )
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> START_FADING_AT = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("startFadingAt")
      .setDefaultValue(0.0)
      .setDisplayName("gui.xaero_start_fading_at")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(0)
      .setUiLastOption(256)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> (int)x.doubleValue())
      .setUiValueNameProvider(x -> x.intValue() == 0 ? class_1074.method_4662("gui.xaero_start_fading_at_auto", new Object[0]) : x.intValue() + "")
      .setTooltip(new CursorBox("gui.xaero_box_start_fading_at"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> ENTITY_NUMBER = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("entityNumber")
      .setDefaultValue(1000.0)
      .setDisplayName("gui.xaero_entity_amount")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(0)
      .setUiLastOption(10)
      .setIndexReader(x -> (double)x * 100.0)
      .setIndexWriter(x -> (int)(x / 100.0))
      .setUiValueNameProvider(x -> x.intValue() == 0 ? class_1074.method_4662("gui.xaero_unlimited", new Object[0]) : x.intValue() + "")
      .setTooltip(new CursorBox("gui.xaero_box_entity_amount"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Boolean> ALWAYS_NAMETAGS = ObjectCategorySetting.Builder.<Boolean>getDefault()
      .setId("alwaysDisplayNametags")
      .setDefaultValue(false)
      .setDisplayName("gui.xaero_always_entity_nametags")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(1)
      .setIndexReader(x -> x == 1)
      .setIndexWriter(x -> x ? 1 : 0)
      .setUiValueNameProvider(ModSettings::getTranslation)
      .setTooltip(new CursorBox("gui.xaero_box_always_entity_nametags2"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Boolean> ICON_NAME_FALLBACK = ObjectCategorySetting.Builder.<Boolean>getDefault()
      .setId("displayNameWhenIconFails")
      .setDefaultValue(true)
      .setDisplayName("gui.xaero_entity_icon_name_fallback")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(1)
      .setIndexReader(x -> x == 1)
      .setIndexWriter(x -> x ? 1 : 0)
      .setUiValueNameProvider(ModSettings::getTranslation)
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> RENDER_OVER_MINIMAP = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("renderOverMinimapFrame")
      .setDefaultValue(1.0)
      .setDisplayName("gui.xaero_radar_render_over_minimap")
      .setSettingUIType(CategorySettingsUIEditorSettingType.ITERATION_BUTTON)
      .setUiFirstOption(0)
      .setUiLastOption(2)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(x -> class_1074.method_4662(ModSettings.RADAR_OVER_MAP_OPTIONS[x.intValue()], new Object[0]))
      .setTooltip(new CursorBox("gui.xaero_box_radar_render_over_minimap"))
      .build(SETTINGS, SETTINGS_LIST);
   public static final ObjectCategorySetting<Double> RENDER_ORDER = ObjectCategorySetting.Builder.<Double>getDefault()
      .setId("renderOrder")
      .setDefaultValue(0.0)
      .setDisplayName("gui.xaero_radar_render_order")
      .setSettingUIType(CategorySettingsUIEditorSettingType.SLIDER)
      .setUiFirstOption(0)
      .setUiLastOption(1000)
      .setIndexReader(x -> (double)x)
      .setIndexWriter(x -> x.intValue())
      .setUiValueNameProvider(x -> x.intValue() + "")
      .setTooltip(new CursorBox("gui.xaero_box_radar_render_order"))
      .build(SETTINGS, SETTINGS_LIST);
}
